export type ProviderCredential = { provider: string; key_name: string; pool_id: string };
export type Project = { id: string; name: string; enabled: boolean; monthly_budget_usd: number; credentials?: ProviderCredential[] };
export type PriceWindow = {
	id: string;
	label: string;
	days: number[];
	start: string;
	end: string;
	input_usd_per_million: number;
	output_usd_per_million: number;
	cached_input_usd_per_million?: number;
	image_usd_per_image?: number;
};
export type PriceSchedule = {
	timezone: string;
	calendar_timezone?: string;
	default_label: string;
	excluded_dates?: string[];
	windows: PriceWindow[];
};
export type AppliedPrice = {
	label: string;
	window_id: string;
	timezone: string;
	priced_at: string;
	cached_input_tokens: number;
	cache_usage_known: boolean;
	usage_known?: boolean;
	cache_write_tokens?: number;
	cache_write_usage_known?: boolean;
	credential_source?: "project" | "default" | "profile_default";
	official_source_url?: string;
	official_source_hash?: string;
	official_verified_at?: string;
};
export type Profile = {
	id: string;
	provider: string;
	model: string;
	key_name: string;
	pool_id: string;
	max_output_tokens: number;
	input_usd_per_million: number;
	output_usd_per_million: number;
	cached_input_usd_per_million?: number;
	pricing?: PriceSchedule;
	applied_price?: AppliedPrice;
	follow_official?: boolean;
	official_terms?: string;
	official_calendar_year?: number;
	official_calendar_hash?: string;
	image_usd_per_image?: number;
	image_size?: string;
	image_quality?: string;
};
export type Scene = {
	id: string;
	project_id: string;
	name: string;
	profiles: string[];
	endpoint: string;
	queue_timeout_seconds: number;
	timeout_seconds: number;
	retries: number;
	routing_policy?: "ordered" | "lowest_cost";
};
export type PricingResponse = { at: string; profiles: Profile[]; verification: CatalogProfile[] };
export type Pool = { id: string; concurrency: number; queue_size: number; rpm: number; tpm: number };
export type CatalogSettings = { enabled: boolean; interval_minutes: number };
export type Config = {
	projects: Project[];
	profiles: Profile[];
	scenes: Scene[];
	pools: Pool[];
	catalog?: CatalogSettings;
	default_credentials?: ProviderCredential[];
};
export type CatalogQuote = {
	name: string;
	model?: string;
	input: number;
	output: number;
	cached?: number;
	peak?: CatalogQuote;
	automatic: boolean;
	display_only?: boolean;
	conditions: string;
	billing_details?: Record<string, string>;
};
export type CatalogSource = {
	provider: string;
	scope?: string;
	url: string;
	checked_at: string;
	verified_at: string;
	hash: string;
	terms_hash: string;
	error?: string;
	failures: number;
	quotes: CatalogQuote[] | null;
	news_url: string;
	news_checked_at: string;
	news_hash: string;
	news_error?: string;
	news_models: string[] | null;
};
export type CatalogEvent = {
	at: string;
	provider: string;
	model?: string;
	kind: string;
	hash: string;
	before?: CatalogQuote;
	after?: CatalogQuote;
	profiles?: string[];
};
export type CatalogProfile = {
	id: string;
	status: string;
	reason: string;
	source_url?: string;
	verified_at: string;
	can_apply: boolean;
	quote?: CatalogQuote;
	hash?: string;
};
export type CatalogResponse = {
	settings: CatalogSettings;
	sources: CatalogSource[];
	events: CatalogEvent[];
	profiles: CatalogProfile[];
	running: boolean;
	next_checks: Record<string, string>;
	at: string;
};
export type Entity = "projects" | "profiles" | "scenes" | "pools";
export type ConfigResponse = { config: Config; version: number };
export type Key = { id: string; project_id: string; prefix: string; created_at: string; revoked: boolean };
export type Usage = {
	project_id: string;
	month: string;
	attempts: number;
	input_tokens: number;
	output_tokens: number;
	cost_usd: number;
	reserved_usd: number;
	errors: number;
};
export type Attempt = {
	prediction?: CostPrediction;
	price_snapshot?: Profile;
	id: string;
	request_id: string;
	project_id: string;
	scene_id: string;
	profile_id: string;
	provider: string;
	model: string;
	status: string;
	http_status: number;
	input_tokens: number;
	output_tokens: number;
	cost_usd: number;
	estimated: boolean;
	queue_ms: number;
	duration_ms: number;
	created_at: string;
};
export type CostPrediction = {
	cost_usd: number;
	uncached_usd: number;
	reservation_usd: number;
	input_tokens: number;
	output_tokens: number;
	expected_cached_tokens: number;
	cache_hit_probability: number | null;
	confidence: "low" | "medium" | "high";
	cache_confidence: "unknown" | "low" | "medium" | "high";
	samples: number;
	cache_samples: number;
	method: string;
	at: string;
	cache_horizon_seconds: number;
	error_usd?: number;
};
export type EstimateResponse = { candidates: { profile_id: string; prediction: CostPrediction | null; error?: string }[]; at: string };
export type PoolStats = Pool & {
	active: number;
	queued: number;
	requests_in_window: number;
	tokens_in_window: number;
	cooldown_until?: string;
};
export type Breakdown = {
	project_id: string;
	scene_id: string;
	profile_id: string;
	provider: string;
	model: string;
	attempts: number;
	input_tokens: number;
	output_tokens: number;
	cost_usd: number;
	estimated_attempts: number;
};
export type Overview = {
	demo: boolean;
	month: string;
	usage: Usage[];
	recent: Attempt[];
	breakdown: Breakdown[];
	pools: PoolStats[];
	pending: number;
	pending_limit: number;
};