// Standalone companion-console QA. No provider credentials or live model calls.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";
import path from "node:path";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.LLMHUB_PLAYWRIGHT_MODULE || "playwright");
const url = process.env.LLMHUB_TEST_URL || "http://127.0.0.1:8090";
const admin = process.env.LLMHUB_TEST_ADMIN || "llmhub-local-demo-admin-token";
const output = path.resolve("test-results/llmhub");
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const watchdog = setTimeout(() => { console.error("llmHub browser QA exceeded 90 seconds"); process.exit(1); }, 90000);
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(12000);
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(url);
  await page.getByTestId("hub-admin-token").fill("invalid-admin-token-24-characters");
  await page.getByTestId("hub-login").click();
  await page.getByRole("alert").waitFor();
  await page.getByTestId("hub-admin-token").fill(admin);
  await page.getByTestId("hub-login").click();
  await page.locator(".metrics").waitFor();
  await page.getByTestId("hub-request-row").first().waitFor();
  await page.screenshot({ path: path.join(output, "desktop-overview.png") });
  for (const view of ["projects", "scenes", "profiles", "pools", "requests", "usage", "keys", "settings"]) {
    await page.getByTestId(`hub-nav-${view}`).click();
    await page.locator(".page-heading h1").waitFor();
    const overflowing = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
    assert.equal(overflowing, false, `${view} overflows desktop viewport`);
  }
  await page.getByTestId("hub-nav-projects").click();
  await page.getByTestId("hub-create").click();
  const id = `qa-${Date.now()}`;
  await page.getByTestId("hub-field-id").fill(id);
  await page.getByTestId("hub-field-name").fill("QA Project");
  await page.getByTestId("hub-field-monthly_budget_usd").fill("25");
  await page.getByTestId("hub-editor-save").click();
  await page.locator("dialog").waitFor({ state: "hidden" });
  const row = page.getByRole("row").filter({ hasText: id });
  await row.waitFor();
  await row.getByTestId("hub-edit").click();
  await page.getByTestId("hub-field-name").fill("QA Project Updated");
  await page.getByTestId("hub-editor-save").click();
  await page.locator("dialog").waitFor({ state: "hidden" });
  assert.match(await row.innerText(), /QA Project Updated/);
  await row.getByTestId("hub-delete").click();
  await page.getByTestId("hub-delete-confirm").click();
  await row.waitFor({ state: "hidden" });
  await page.getByTestId("hub-nav-keys").click();
  await page.getByTestId("hub-key-project").selectOption("storepilot");
  await page.getByTestId("hub-key-create").click();
  const secret = await page.getByTestId("hub-key-secret").innerText();
  assert.equal(secret.startsWith("lh_"), true, "project key has an invalid prefix");
  await page.getByTestId("hub-key-dismiss").click();
  const image = await page.request.post(`${url}/v1/images/generations`, { headers: { Authorization: `Bearer ${secret}` }, data: { model: "scene/image.generate", prompt: "local mock image" } });
  assert.equal(image.status(), 200, await image.text());
  assert.equal((await image.json()).data.length, 1);
  const stream = await page.request.post(`${url}/v1/chat/completions`, { headers: { Authorization: `Bearer ${secret}` }, data: { model: "scene/text.generate", messages: [{ role: "user", content: "local stream" }], stream: true } });
  assert.equal(stream.status(), 200);
  assert.match(await stream.text(), /\[DONE\]/);
  const keyRow = page.getByRole("row").filter({ hasText: secret.slice(0, 11) });
  await keyRow.getByTestId("hub-key-revoke").click();
  await page.getByTestId("hub-revoke-confirm").click();
  await page.locator("dialog").waitFor({ state: "hidden" });
  const rejected = await page.request.post(`${url}/v1/chat/completions`, { headers: { Authorization: `Bearer ${secret}` }, data: { model: "scene/text.generate", messages: [{ role: "user", content: "revoked" }] } });
  assert.equal(rejected.status(), 401);
  await page.getByTestId("hub-nav-overview").click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(output, "mobile-overview.png") });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, "mobile overview overflow");
  await page.getByTitle("菜单", { exact: true }).click();
  await page.getByTestId("hub-nav-projects").click();
  await page.getByTestId("hub-create").click();
  await page.screenshot({ path: path.join(output, "mobile-editor.png") });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, "mobile editor overflow");
  await page.getByRole("button", { name: "取消", exact: true }).click();
  assert.deepEqual(errors, [], "uncaught browser errors");
  console.log("PASS: login recovery, nine views, project CRUD, key issuance/revocation, image, SSE, desktop/mobile layout; screenshots in test-results/llmhub");
} finally { clearTimeout(watchdog); await browser.close(); }
